### ISSUE TITLE
Jobs created by the gem do not have exact case for names

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/neeto-monitor-ruby#18]
https://github.com/bigbinary/neeto-monitor-web/issues/233

**Comment by datt** [comment]
@datt _a

**Comment by sandip-mane** [comment]
@jijinharidas _a please take it up. Take help from Datt if needed.

**Comment by datt** [comment]
@datt _a

**Comment by datt** [comment]
I checked the issue. The gem does not have this issue, the application is modifying it. Closing this and will re-open the main issue.
